version: '3.8'

services:
  backend:
    build: .
    depends_on:
      - redis
      - rabbitmq
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:5000"

  redis:
    image: "redis:latest"
    restart: always
    ports:
      - "6379:6379"

  rabbitmq:
    image: "rabbitmq:management"
    restart: always
    ports:
      - "5672:5672"  # RabbitMQ message broker port
      - "15672:15672"  # RabbitMQ management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest